//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace codebiz_employee_management.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class employee
    {
        public int employeeId { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string firstName { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string middleName { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string lastName { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string contactNumber { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string address { get; set; }
    }
}
